import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "CALLCORD",
  description:
    "Real-time chat, voice, and community features in a modern, scalable Next.js 14-powered platform.",
  icons: {
    icon: "/iconoficial.png",
    shortcut: "/iconoficial.png",
    apple: "/iconoficial.png",
  },
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "liveblocks",
    "livekit",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "discord-clone",
    "realtime-chat",
    "live-audio",
    "live-video",
    "live-chat",
    "neon-db",
    "sonner",
    "zustand",
    "zod",
    "sql",
    "postgresql",
    "aiven",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Saimon",
    url: "#",
  },
} as const;
